# Netlify configuration for The Beanery Frontend
# This file is at repository root

[build]
  # Build command - navigate to thebeanery first
  command = "cd thebeanery && npm install && npm run build"
  
  # Directory with the build output (relative - Netlify auto-adds thebeanery/)
  publish = "dist"

# Production environment variables
[build.environment]
  NODE_VERSION = "20"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Context-specific configurations
[context.production]
  command = "npm run build"
  
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

