# Netlify configuration for The Beanery Frontend

[build]
  # Directory where the build command should run
  base = "/"
  
  # Build command
  command = "npm run build"
  
  # Directory with the build output
  publish = "dist"

# Production environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Build plugin for caching
[[plugins]]
  package = "@netlify/plugin-caching"

# Context-specific configurations
[context.production]
  command = "npm run build"
  
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Dev server configuration (optional)
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"

